[[plugins]]
package = "@netlify/plugin-sitemap"

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"

  [[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
  filePath = "/sitemap.xml"

  [[redirects]]
  from = "/"
  to = "/index.html"
  status = 200